---
id: tokyodebian-debbugs-soap-20170520
base_name: debbugs-soap
tags:
- rabbit
- debbugs
presentation_date: 
version: 2017.05.20.1
licenses: 
- CC-BY-SA-4.0
slideshare_id: 
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: Kentaro Hayashi
  email: kenhys@gmail.com
  rubygems_user: kenhys
  slideshare_user: 
  speaker_deck_user: 
